# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install uv for faster dependency resolution
      - pip install uv
    post_install:
      # Install dependencies using uv
      - uv pip install -e .[dev]
      - uv pip install sphinx sphinx-rtd-theme myst-parser

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
